stages:
  data:
    cmd: python src/data_processing.py
    deps:
      - data/train.csv
      - data/test.csv
    outs:
      - data/processed_train.csv
      - data/processed_test.csv
  train:
    cmd: python src/train.py
    deps:
      - data/processed_train.csv
      - data/processed_test.csv
    outs:
      - models/best_model.pkl
